name: text_to_pdf
description: A package to convert string into pdf file.
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
dependencies:
  path: ^1.8.3
  path_provider: ^2.0.15
  pdf: ^3.10.3
dependency_overrides:
  image: 4.0.17

  flutter:
    sdk: flutter
