name: text_to_pdf
description: A package to convert string into pdf file.
version: 1.0.0

environment:
  sdk: '>=2.19.5 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
dependencies:
  path: ^1.8.2
  path_provider: ^2.0.14
  pdf: ^3.10.1

  flutter:
    sdk: flutter
